
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks2-cjones-profile-platform-apps
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/chrisj-platform9/arlon-examples
    path: profiles/platform-apps/mgmt
    targetRevision: HEAD
    helm:
      parameters:
      - name: clusterName
        value: eks2-cjones
      - name: profileAppName
        value: eks2-cjones-profile-platform-apps
